version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "jekyll"
        versions:
          - "4.4.1" # Ignore this specific version