port: 4003
title: HEAL610
description: These are my course notes for HEAL610. The site also includes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# The base URL of your site when hosted
url: "https://alainparadis.github.io/HEAL610"

# The subdirectory for your repository (leave empty for root-level sites)
baseurl: ""

plugins:
  - jekyll-datapage-generator

page_gen:
  - data: 'sources' # Name of your CSV file (without extension)
    template: 'sources' # Layout template for individual pages
    name: 'Key' # Column to use for naming each page
    dir: 'sources' # Directory where pages will be generated

defaults:
  - scope:
      path: "sources"
    values:
      layout: "sources"

exclude:
- .DS_Store
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- vendor/
