port: 4003
title: HEAL610
description: These are my course notes for HEAL610. The site also includes
# theme: just-the-docs

# The base URL of your site when hosted
url: "https://alainparadis.github.io/HEAL610"

# The subdirectory for your repository (leave empty for root-level sites)
baseurl: ""

# Example:
# If your GitHub Pages site is hosted at https://username.github.io/my-site,
# set baseurl to "/my-site".


url: https://just-the-docs.github.io

exclude:
- .DS_Store
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- vendor/
